<a href="https://colab.research.google.com/github/sanrajbandre/parallel-computing.github.io/blob/parallel-computing-colab/colab/parallel_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# DEVICE VERIFICATION

!nvidia-smi
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
device_name = pynvml.nvmlDeviceGetName(handle)
#if device_name != b'Tesla K80':
if device_name != b'Tesla K80':
  raise Exception("Unfortunately this instance does not have a Tesla K80...!")
else:
  print('GPU DEVICE GETS VERIFIED...!')



Sat Jul 11 15:03:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [7]:
import pynvml

pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
device_name = pynvml.nvmlDeviceGetName(handle)
print(device_name)

b'Tesla K80'


In [8]:
# IMPORT 
import pandas as pd
import io
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('demo.csv')
df

Saving demo.csv to demo.csv


ID                 PRODUCT          TYPE  UNIT     COST
0  1000001  PRODUCT_SERIES_1000001   SLIDE-PHONE     2  23149.0
1  1000002  PRODUCT_SERIES_1000002   SLIDE-PHONE     2  16849.0
2  1000003  PRODUCT_SERIES_1000003  KEYPAD-PHONE     1  44037.0
3  1000004  PRODUCT_SERIES_1000004  KEYPAD-PHONE     1  32585.0
4  1000005  PRODUCT_SERIES_1000005  KEYPAD-PHONE     1  26841.0
5  1000006  PRODUCT_SERIES_1000006  KEYPAD-PHONE     1  60725.0
6  1000007  PRODUCT_SERIES_1000007   SLIDE-PHONE     2  88327.0
7  1000008  PRODUCT_SERIES_1000008  KEYPAD-PHONE     1  90369.0
8  1000009  PRODUCT_SERIES_1000009   APPLE-PHONE     3  35244.0

In [10]:
# INSTALL PYCUDA ON NOTEBOOK INSTANCE
! pip3 install pycuda

     |████████████████████████████████| 1.6MB 2.7MB/s 
     |████████████████████████████████| 71kB 7.3MB/s 
     |████████████████████████████████| 81kB 7.4MB/s 
  Created wheel for pycuda: filename=pycuda-2019.1.2-cp36-cp36m-linux_x86_64.whl size=4536962 sha256=4323a0d0cc2dd6b9fc4051302382a93b3e9867e2adb4ccd3c265046b15c3db4a
  Stored in directory: /root/.cache/pip/wheels/a6/60/f0/b1c430c73d281ac3e46070480db50f7907364eb6f6d3188396
  Created wheel for pytools: filename=pytools-2020.3.1-py2.py3-none-any.whl size=65243 sha256=f6fa134d10e40e76609596d54715bd7875902f1123e5404a236e2cc639bb6d2e
  Stored in directory: /root/.cache/pip/wheels/ac/01/07/fe484d8aae398b7f6150dae468a53887f0e7e265f1fc7fc975
Successfully built pycuda pytools
[[ 0.44074079 -2.78023543 -0.53198789  1.40230184]]
[[ 0.88148158 -5.56047086 -1.06397579  2.80460367]]


In [11]:
import pycuda.gpuarray as gpuarray
import pycuda.driver as cuda
import pycuda.autoinit
import numpy
a_gpu = gpuarray.to_gpu(numpy.random.randn(1,4).astype(numpy.float64))
a_doubled = (2*a_gpu).get()

print (a_gpu)
print (a_doubled)

[[ 0.18390399 -0.17670286  0.86340379 -1.30025133]]
[[ 0.36780798 -0.35340572  1.72680757 -2.60050267]]
